### ISSUE TITLE
Problem selecting a row when clicking on a cell

### ISSUE THREAD

**Issue by RaimundBarbeln** [datenhahn/componentrenderer#11]
Hi,

You cannot select a row when you click to the right of a component within a cell.
Clicking to the left of the component correctly selects the row.

This can be seen in the demo project

This is kind of a show stopper for me, since it also does not fire the Click event for the grid, which I need for som columns.

**Comment by datenhahn** [comment]
Confirmed. I think the simplepanel which holds the components does not propagate the clicks to the grid, will look into it tonight

**Comment by datenhahn** [comment]
Thank you Raimund for opening the issue, I am grateful for any bug-reports/feature wishes to further improve the renderer.

Clicks to the SimplePanel containing the components, or to layout-components now trigger row selection. Clicks to components inside a layout do not trigger selection, as it would confuse the user. Please check if that fits your needs and reopen the ticket otherwise.

![Layers with trigger selection](https://raw.githubusercontent.com/datenhahn/componentrenderer/master/doc/issue11_select_row_fix.png)
